-- AlterTable
ALTER TABLE "Bed" ADD COLUMN "gardenX" INTEGER;
ALTER TABLE "Bed" ADD COLUMN "gardenY" INTEGER;

-- CreateTable
CREATE TABLE "Garden" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT DEFAULT 1,
    "widthInches" INTEGER NOT NULL,
    "heightInches" INTEGER NOT NULL,
    "cellInches" INTEGER NOT NULL DEFAULT 12,
    "updatedAt" DATETIME NOT NULL
);
